id: P003049
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 10:37:02.220882
source_metadata:
  id: bdr:W3CN2172
  title: གསེར་ཐར་རྫོང་གི་ས་ཆའི་མིང་བཏུས།
  author: ''
  volumes:
    f2a4111628214a7dbf3d5f7e35354346:
      image_group_id: I3CN2174
      title: ''
      volume_number: 1
      total_pages: 131
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
